### PR TITLE
Update to purescript 0.13.0

### PR DESCRIPTION
**Pull request by felixSchl**
* Update ansi escape sequences to be in hex format
* Update purescript-record dependency
* Drop dependency on purescript-typelevel-prelude
  See: https://github.com/purescript/purescript-record/commit/8837dcde97a11ac6ef108bcf7dcecd7fc57abf5a

### CODE REVIEW

**Comment by hdgarrood** [comment]
Can you please change the record dependency to >=1.0.0 <3.0.0 so that we aren’t tightening the lower bound unnecessarily?

**Comment by felixSchl** [comment]
But it does not compile with 1.0.0:

```
Error found:
in module Type.Row
at bower_components/purescript-typelevel-prelude/src/Type/Row.purs:4:5 - 4:24 (line 4, column 5 - line 4, column 24)

  Export for type Prim.RowList.Cons conflicts with type class Prim.Row.Cons
```

**Comment by hdgarrood** [comment]
That’s only true if you’re using 0.13.x. It will still work with 0.12.x.

**Comment by felixSchl** [comment]
Updated

**Comment by hdgarrood** [comment]
Thank you

**Pull request merged**
